spring:
  application:
    name: ai-agent
  profiles:
    default: local
  config:
    import:
      - optional:classpath:app-session.yml
      - optional:classpath:app-rag.yml

server:
  port: 8081

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:mapper/*.xml
  type-aliases-package:
    - com.example.agent.core.entity
    - com.example.agent.rag.entity
    - com.example.agent.skills.entity
    - com.example.agent.api.entity
  type-handlers-package:
    - com.example.agent.core.handle
    - com.example.agent.rag.handle
    - com.example.agent.skills.handle
    - com.example.agent.api.handle
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-fetch-size: 100
    default-statement-timeout: 30
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
